PedaleaWEB/Controllers/Pedalea/PedaleaController.cs
using Microsoft.AspNetCore.Mvc;

namespace PedaleaWEB.Controllers.Pedalea
{
    public class PedaleaController : Controller
    {
        public IActionResult Gestion()
        {
            return View();
        }
    }
}

PedaleaWEB/Controllers/Persona/PersonaController.cs
using CanonicalModel.Model.Configuration;
using CanonicalModel.Model.Entity.Persona;
using Microsoft.AspNetCore.Mvc;
using System.Text;
using System.Text.Json;

namespace PedaleaWEB.Controllers.Persona
{
    public class PersonaController : Controller
    {
        [HttpGet]
        public IActionResult Gestion()
        {
            return View();
        }

    }
}

PedaleaWEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PedaleaWEB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PedaleaWEB.styles.css" asp-append-version="true" />
    <link href="~/" rel="stylesheet" />
    <link href="~/lib/dataTables-1.11.3/css/dataTables.bootstrap5.min.css" rel="stylesheet" />
    <link href="~/lib//toastr.js/toastr.min.css" rel="stylesheet" />
    <link href="~/lib/select2/css/select2.min.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <style>
        .checkbox{
            transform:scale(2)
        }
    </style>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/dataTables-1.11.3/js/jquery.dataTables.min.js" asp-append-version="true"></script>
    <script src="~/lib/dataTables-1.11.3/js/dataTables.bootstrap5.min.js" asp-append-version="true"></script>
    <script src="~/lib/toastr.js/toastr.min.js" asp-append-version="true"></script>
    <script src="~/lib/select2/js/select2.min.js"></script>
    <script src="~/lib/Local//miles.js"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PedaleaWEB</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Persona" asp-action="Gestion">Persona</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pedalea" asp-action="Gestion">Bicycle Shop</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - PedaleaWEB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>*@

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>